[project]
name = "unidad04"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Yunior Laureano", email = "YLaureano@dacgroup.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
unidad04 = "unidad04:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
