[project]
name = "lab02"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Yunior Laureano", email = "yuniorlaureano@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.3.0",
    "pandas>=3.0.6",
    "pytest>=9.1.1",
    "scikit-learn>=1.9.1",
    "ucimlrepo>=0.0.7",
]

[project.scripts]
lab02 = "lab02:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
